# Generated by Django 3.0.3 on 2020-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='idnum',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID Number'),
            preserve_default=False,
        ),
    ]
