# Generated by Django 3.0.3 on 2020-05-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200506_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='idnum',
            field=models.IntegerField(null=True, unique=True, verbose_name='ID Number'),
        ),
    ]
