# Generated by Django 3.0.3 on 2020-05-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200506_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='idnum',
        ),
        migrations.AddField(
            model_name='account',
            name='id_num',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID Number'),
            preserve_default=False,
        ),
    ]
