# Generated by Django 3.0.3 on 2020-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200506_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='idnum',
            field=models.IntegerField(unique=True, verbose_name='ID Number'),
        ),
    ]
