# Generated by Django 3.0.3 on 2020-05-05 13:09

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookreservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreservation',
            old_name='date',
            new_name='date_reservation',
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='date_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Date returned: '),
        ),
        migrations.AddField(
            model_name='bookreservation',
            name='due_back',
            field=models.DateField(default=catalog.models.default_due, verbose_name='Due back: '),
        ),
    ]
