# Generated by Django 3.0.3 on 2020-05-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200505_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreservation',
            options={'ordering': ['due_back']},
        ),
    ]
