# Generated by Django 3.0.3 on 2020-05-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200505_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreservation',
            options={'ordering': ['-date_reservation']},
        ),
        migrations.RemoveField(
            model_name='bookreservation',
            name='due_back',
        ),
    ]
