# Generated by Django 3.0.3 on 2020-05-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200505_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.ManyToManyField(null=True, to='catalog.BookReview'),
        ),
    ]
