# Generated by Django 3.0.3 on 2020-05-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_bookreview_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
