# Generated by Django 3.0.3 on 2020-05-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_bookreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={},
        ),
    ]
